# Generated by Django 2.2.10 on 2020-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('clike', 'c/c++'), ('clike', 'text/x-java'), ('javascript', 'javascript'), ('python', 'python')], default='python', max_length=100),
        ),
    ]
