# Generated by Django 2.2.10 on 2020-02-25 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0002_auto_20200225_2343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snippet',
            unique_together={('owner', 'name')},
        ),
    ]
