# Generated by Django 2.2.10 on 2020-02-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200225_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='indent_mode',
            field=models.CharField(choices=[('tabs', 'Tabs'), ('spaces', 'Spaces')], default='spaces', max_length=10),
        ),
        migrations.AddField(
            model_name='snippet',
            name='ndent_value',
            field=models.PositiveIntegerField(choices=[(2, 2), (4, 4), (8, 8)], default=2),
        ),
    ]
