# Generated by Django 2.2.10 on 2020-02-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200226_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='ndent_value',
            new_name='indent_value',
        ),
    ]
